import os
from pathlib import Path


IDE_CONFIG = {
    "cursor": {"filename": ".cursorrules", "display": "Cursor"},
    "windsurf": {"filename": ".windsurfrules", "display": "Windsurf"},
    "antigravity": {"filename": ".antigravity/context.md", "display": "Antigravity"},
}


def write_rules(project_root: str, ide: str, content: str, task: str = "", language: str = "") -> str:
    """Write rules content to the appropriate file for the IDE."""
    config = IDE_CONFIG.get(ide.lower())
    if not config:
        raise ValueError(f"Unknown IDE: {ide}")

    root = Path(project_root)
    filename = config["filename"]
    output_path = root / filename

    # Create parent directory if needed (for Antigravity)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Prepend header for Antigravity
    write_content = content
    if ide.lower() == "antigravity":
        header = f"""# Project context
> Auto-generated by ContextForge
> Task: {task}
> Language: {language}

"""
        write_content = header + content

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(write_content)

    return str(output_path.absolute())


def detect_ide(project_root: str) -> str | None:
    """Detect which IDE is being used based on marker files/directories."""
    root = Path(project_root)

    # Check for Cursor
    if (root / ".cursorrules").exists() or (root / ".cursor").exists():
        return "cursor"

    # Check for Windsurf
    if (root / ".windsurfrules").exists() or (root / ".windsurf").exists():
        return "windsurf"

    # Check for Antigravity
    if (root / ".antigravity").exists():
        return "antigravity"

    return None
